### ISSUE TITLE
Que tipo de pergunta eu faço aqui?

### ISSUE THREAD

**Issue by Rich14S** [Rich14S/OMG_BADGES#3]
Alguém me explica?

**Comment by roodriiigooo** [comment]
> Alguém me explica?

Nesta sessão você pode se comunicar com as pessoas que vão contribuir de alguma forma com o seu projeto, responder dúvidas ou até mesmo ter ajuda pra corrigir bugs!

**Comment by Rich14S** [comment]
Oh! Legal! Muito obrigado!
